services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: janawat_db
    volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'

# docker-compose up -d
# docker-compose down